version: "3.9"

services:
  # This is the name of the service you run in terminal
  # sudo docker-compose up python-tests
  python-tests:
    build:
      context: .
      dockerfile: Dockerfile

    # The infinite loop ensures the dockerfile keeps running
    command: "python -c 'while True: pass'"

    container_name: pyspark_container

    volumes:
      - ./exercise_files:/app/exercise_files
      - ./mycode:/app/mycode

    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      # POSTGRES_PASSWORD is required for you to use the PostgreSQL image
      POSTGRES_PASSWORD: example
      # POSTGRES_DB defines a different name for the default database
      POSTGRES_DB: etl_pipeline